- title: The Political groups of the European Parliament
  url: https://www.europarl.europa.eu/about-parliament/en/organisation-and-rules/organisation/political-groups
  date: 2024-07-16

- title: National Council (Austria)
  url: https://en.wikipedia.org/wiki/National_Council_(Austria)
  date: 2025-03-14
